services:
  app:
    build: .
    environment:
    - PGHOST=db
    - PGUSER=postgres
    - PGPASSWORD=example
    - PGDATABASE=postgres
    - PGPORT=5432
    - PGPOOLSIZE=10
    depends_on:
    - db
    networks:
      appnet:
        aliases:
          - app

  lb:
    image: nginx:latest
    container_name: lb
    ports:
      - "3000:80"   # External port 3000 mapped to NGINX
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - appnet

  db:
    image: postgres:15
    environment:
    - POSTGRES_PASSWORD=example
    volumes:
    - db-data:/var/lib/postgresql/data
    - ./init/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
    - appnet


  prometheus:
    image: prom/prometheus:latest
    volumes:
    - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
    - "9090:9090"
    depends_on:
    - app
    networks:
    - appnet


  grafana:
    image: grafana/grafana:latest
    ports:
    - "3001:3000"
    environment:
    - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
    - grafana-data:/var/lib/grafana
    depends_on:
    - prometheus
    networks:
    - appnet
      
  postgres-exporter:
    image: quay.io/prometheuscommunity/postgres-exporter:latest
    container_name: postgres-exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:example@db:5432/postgres?sslmode=disable"
    networks:
      - appnet
    ports:
      - "9187:9187"
    restart: unless-stopped
    depends_on:
      - db



volumes:
  db-data:
  grafana-data:


networks:
  appnet:
    driver: bridge