global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'node_app'
    static_configs:
      - targets: ['app:3000']
    metrics_path: /metrics

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
